
package no.uib.mitraq.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 * A dialog displaying various filters that can be applied to the protein results
 * table.
 *
 * @author Harald Barsnes
 */
public class ResultsFilter extends javax.swing.JDialog {

    /**
     * The protein results table.
     */
    private JTable resultsTable;
    /**
     * The MiTRAQ parent frame.
     */
    private MiTRAQ miTraq;

    /**
     * Creates a new ResultsFilter dialog.
     *
     * @param miTraq the MiTRAQ parent frame
     * @param modal if the dialog is modal or not
     * @param currentFilterValues the current filter text values
     * @param currrentFilterRadioButtonSelections the current filter radio button settings
     */
    public ResultsFilter(MiTRAQ miTraq, boolean modal, String[] currentFilterValues, Integer[] currrentFilterRadioButtonSelections) {
        super(miTraq, modal);

        this.miTraq = miTraq;

        resultsTable = miTraq.getResultsTable();

        initComponents();

        // update the filter properties
        proteinJTextField.setText(currentFilterValues[0]);
        peptidesJTextField.setText(currentFilterValues[1]);
        coverageJTextField.setText(currentFilterValues[2]);
        expCountJTextField.setText(currentFilterValues[3]);
        foldChangeJTextField.setText(currentFilterValues[4]);
        pValueJTextField.setText(currentFilterValues[5]);
        qValueJTextField.setText(currentFilterValues[6]);

        peptidesGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[0].intValue() == 0);
        peptidesEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[0].intValue() == 1);
        peptidesLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[0].intValue() == 2);

        coverageGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[1].intValue() == 0);
        coverageEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[1].intValue() == 1);
        coverageLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[1].intValue() == 2);

        expCountGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[2].intValue() == 0);
        expCountEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[2].intValue() == 1);
        expCountLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[2].intValue() == 2);

        foldChangeGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[3].intValue() == 0);
        foldChangeEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[3].intValue() == 1);
        foldChangeLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[3].intValue() == 2);

        pValueGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[4].intValue() == 0);
        pValueEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[4].intValue() == 1);
        pValueLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[4].intValue() == 2);

        qValueGreaterThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[5].intValue() == 0);
        qValueEqualJRadioButton.setSelected(currrentFilterRadioButtonSelections[5].intValue() == 1);
        qValueLessThanJRadioButton.setSelected(currrentFilterRadioButtonSelections[5].intValue() == 2);

        setLocationRelativeTo(miTraq);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peptidesButtonGroup = new javax.swing.ButtonGroup();
        coverageButtonGroup = new javax.swing.ButtonGroup();
        expCountButtonGroup = new javax.swing.ButtonGroup();
        foldChangeButtonGroup = new javax.swing.ButtonGroup();
        pValueButtonGroup = new javax.swing.ButtonGroup();
        qValueButtonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        proteinJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        peptidesJTextField = new javax.swing.JTextField();
        coverageJTextField = new javax.swing.JTextField();
        foldChangeJTextField = new javax.swing.JTextField();
        expCountJTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pValueJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        qValueJTextField = new javax.swing.JTextField();
        peptidesGreaterThanJRadioButton = new javax.swing.JRadioButton();
        peptidesEqualJRadioButton = new javax.swing.JRadioButton();
        peptidesLessThanJRadioButton = new javax.swing.JRadioButton();
        coverageGreaterThanJRadioButton = new javax.swing.JRadioButton();
        coverageEqualJRadioButton = new javax.swing.JRadioButton();
        coverageLessThanJRadioButton = new javax.swing.JRadioButton();
        expCountGreaterThanJRadioButton = new javax.swing.JRadioButton();
        expCountEqualJRadioButton = new javax.swing.JRadioButton();
        expCountLessThanJRadioButton = new javax.swing.JRadioButton();
        foldChangeGreaterThanJRadioButton = new javax.swing.JRadioButton();
        foldChangeEqualJRadioButton = new javax.swing.JRadioButton();
        foldChangeLessThanJRadioButton = new javax.swing.JRadioButton();
        pValueGreaterThanJRadioButton = new javax.swing.JRadioButton();
        pValueEqualJRadioButton = new javax.swing.JRadioButton();
        pValueLessThanJRadioButton = new javax.swing.JRadioButton();
        qValueGreaterThanJRadioButton = new javax.swing.JRadioButton();
        qValueEqualJRadioButton = new javax.swing.JRadioButton();
        qValueLessThanJRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        clearJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Results Filter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Results Fillter"));

        jLabel9.setText("Protein:");

        proteinJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proteinJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                proteinJTextFieldKeyReleased(evt);
            }
        });

        jLabel10.setText("Peptides:");

        jLabel11.setText("Coverage:");

        jLabel12.setText("Exp. Count:");

        jLabel13.setText("Fold Change:");

        peptidesJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peptidesJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                peptidesJTextFieldKeyReleased(evt);
            }
        });

        coverageJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coverageJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coverageJTextFieldKeyReleased(evt);
            }
        });

        foldChangeJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        foldChangeJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                foldChangeJTextFieldKeyReleased(evt);
            }
        });

        expCountJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expCountJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expCountJTextFieldKeyReleased(evt);
            }
        });

        jLabel14.setText("P-value:");

        pValueJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pValueJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pValueJTextFieldKeyReleased(evt);
            }
        });

        jLabel15.setText("Q-value:");

        qValueJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qValueJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qValueJTextFieldKeyReleased(evt);
            }
        });

        peptidesButtonGroup.add(peptidesGreaterThanJRadioButton);
        peptidesGreaterThanJRadioButton.setSelected(true);
        peptidesGreaterThanJRadioButton.setText(">");
        peptidesGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        peptidesButtonGroup.add(peptidesEqualJRadioButton);
        peptidesEqualJRadioButton.setText("=");
        peptidesEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        peptidesButtonGroup.add(peptidesLessThanJRadioButton);
        peptidesLessThanJRadioButton.setText("<");
        peptidesLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        coverageButtonGroup.add(coverageGreaterThanJRadioButton);
        coverageGreaterThanJRadioButton.setSelected(true);
        coverageGreaterThanJRadioButton.setText(">");
        coverageGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        coverageButtonGroup.add(coverageEqualJRadioButton);
        coverageEqualJRadioButton.setText("=");
        coverageEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        coverageButtonGroup.add(coverageLessThanJRadioButton);
        coverageLessThanJRadioButton.setText("<");
        coverageLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        expCountButtonGroup.add(expCountGreaterThanJRadioButton);
        expCountGreaterThanJRadioButton.setSelected(true);
        expCountGreaterThanJRadioButton.setText(">");
        expCountGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        expCountButtonGroup.add(expCountEqualJRadioButton);
        expCountEqualJRadioButton.setText("=");
        expCountEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        expCountButtonGroup.add(expCountLessThanJRadioButton);
        expCountLessThanJRadioButton.setText("<");
        expCountLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        foldChangeButtonGroup.add(foldChangeGreaterThanJRadioButton);
        foldChangeGreaterThanJRadioButton.setSelected(true);
        foldChangeGreaterThanJRadioButton.setText(">");
        foldChangeGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        foldChangeButtonGroup.add(foldChangeEqualJRadioButton);
        foldChangeEqualJRadioButton.setText("=");
        foldChangeEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        foldChangeButtonGroup.add(foldChangeLessThanJRadioButton);
        foldChangeLessThanJRadioButton.setText("<");
        foldChangeLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        pValueButtonGroup.add(pValueGreaterThanJRadioButton);
        pValueGreaterThanJRadioButton.setText(">");
        pValueGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        pValueButtonGroup.add(pValueEqualJRadioButton);
        pValueEqualJRadioButton.setText("=");
        pValueEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        pValueButtonGroup.add(pValueLessThanJRadioButton);
        pValueLessThanJRadioButton.setSelected(true);
        pValueLessThanJRadioButton.setText("<");
        pValueLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        qValueButtonGroup.add(qValueGreaterThanJRadioButton);
        qValueGreaterThanJRadioButton.setText(">");
        qValueGreaterThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        qValueButtonGroup.add(qValueEqualJRadioButton);
        qValueEqualJRadioButton.setText("=");
        qValueEqualJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        qValueButtonGroup.add(qValueLessThanJRadioButton);
        qValueLessThanJRadioButton.setSelected(true);
        qValueLessThanJRadioButton.setText("<");
        qValueLessThanJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("(contains, RegExp)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proteinJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(peptidesJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(coverageJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(expCountJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(pValueJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(foldChangeJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(qValueJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(peptidesGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(peptidesEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(peptidesLessThanJRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(coverageGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coverageEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coverageLessThanJRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(expCountGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(expCountEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(expCountLessThanJRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(foldChangeGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foldChangeEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foldChangeLessThanJRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pValueGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pValueEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pValueLessThanJRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(qValueGreaterThanJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qValueEqualJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qValueLessThanJRadioButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peptidesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(peptidesGreaterThanJRadioButton)
                    .addComponent(peptidesEqualJRadioButton)
                    .addComponent(peptidesLessThanJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(coverageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coverageGreaterThanJRadioButton)
                    .addComponent(coverageEqualJRadioButton)
                    .addComponent(coverageLessThanJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expCountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(expCountGreaterThanJRadioButton)
                    .addComponent(expCountEqualJRadioButton)
                    .addComponent(expCountLessThanJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foldChangeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(foldChangeGreaterThanJRadioButton)
                    .addComponent(foldChangeEqualJRadioButton)
                    .addComponent(foldChangeLessThanJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(pValueGreaterThanJRadioButton)
                    .addComponent(pValueEqualJRadioButton)
                    .addComponent(pValueLessThanJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qValueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(qValueGreaterThanJRadioButton)
                    .addComponent(qValueEqualJRadioButton)
                    .addComponent(qValueLessThanJRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        exitJButton.setText("Exit");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(clearJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitJButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearJButton, exitJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearJButton)
                    .addComponent(exitJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clears all filters.
     *
     * @param evt
     */
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        proteinJTextField.setText(null);
        peptidesJTextField.setText(null);
        coverageJTextField.setText(null);
        expCountJTextField.setText(null);
        foldChangeJTextField.setText(null);
        pValueJTextField.setText(null);
        qValueJTextField.setText(null);
        filter();
    }//GEN-LAST:event_clearJButtonActionPerformed

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void proteinJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proteinJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_proteinJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void peptidesJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_peptidesJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_peptidesJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void coverageJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coverageJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_coverageJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void expCountJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expCountJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_expCountJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void foldChangeJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foldChangeJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_foldChangeJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void pValueJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pValueJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_pValueJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void qValueJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qValueJTextFieldKeyReleased
        filter();
    }//GEN-LAST:event_qValueJTextFieldKeyReleased

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
        filter();
    }//GEN-LAST:event_radioButtonActionPerformed

    /**
     * Saves the filter settings and closes the dialog.
     *
     * @param evt
     */
    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed

        // store the current filter values
        String[] currentFilterValues = {
            proteinJTextField.getText(),
            peptidesJTextField.getText(),
            coverageJTextField.getText(),
            expCountJTextField.getText(),
            foldChangeJTextField.getText(),
            pValueJTextField.getText(),
            qValueJTextField.getText()};

        int peptideRadioButtonIndex = 0;

        if (peptidesEqualJRadioButton.isSelected()) {
            peptideRadioButtonIndex = 1;
        } else if (peptidesLessThanJRadioButton.isSelected()) {
            peptideRadioButtonIndex = 2;
        }

        int coverageRadioButtonIndex = 0;

        if (coverageEqualJRadioButton.isSelected()) {
            coverageRadioButtonIndex = 1;
        } else if (coverageLessThanJRadioButton.isSelected()) {
            coverageRadioButtonIndex = 2;
        }

        int expCountRadioButtonIndex = 0;

        if (expCountEqualJRadioButton.isSelected()) {
            expCountRadioButtonIndex = 1;
        } else if (expCountLessThanJRadioButton.isSelected()) {
            expCountRadioButtonIndex = 2;
        }

        int foldChangeRadioButtonIndex = 0;

        if (foldChangeEqualJRadioButton.isSelected()) {
            foldChangeRadioButtonIndex = 1;
        } else if (foldChangeLessThanJRadioButton.isSelected()) {
            foldChangeRadioButtonIndex = 2;
        }

        int pValueRadioButtonIndex = 0;

        if (pValueEqualJRadioButton.isSelected()) {
            pValueRadioButtonIndex = 1;
        } else if (pValueLessThanJRadioButton.isSelected()) {
            pValueRadioButtonIndex = 2;
        }

        int qValueRadioButtonIndex = 0;

        if (qValueEqualJRadioButton.isSelected()) {
            qValueRadioButtonIndex = 1;
        } else if (qValueLessThanJRadioButton.isSelected()) {
            qValueRadioButtonIndex = 2;
        }

        Integer[] currrentFilterRadioButtonSelections = {
            peptideRadioButtonIndex,
            coverageRadioButtonIndex,
            expCountRadioButtonIndex,
            foldChangeRadioButtonIndex,
            pValueRadioButtonIndex,
            qValueRadioButtonIndex};

        miTraq.setCurrentFilterValues(currentFilterValues);
        miTraq.setCurrrentFilterRadioButtonSelections(currrentFilterRadioButtonSelections);

        // close the dialog
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_exitJButtonActionPerformed

    /**
     * Closes the dialog.
     * 
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exitJButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * Filters the results table according to the current filter settings.
     *
     * @param evt
     */
    private void filter() {

        List<RowFilter<Object, Object>> filters = new ArrayList<RowFilter<Object, Object>>();

        // protein name filter
        String text = proteinJTextField.getText();

        if (text == null || text.length() == 0) {
            filters.add(RowFilter.regexFilter(".*"));
        } else {
            try {
                filters.add(RowFilter.regexFilter(text, resultsTable.getColumn("Protein").getModelIndex()));
            } catch (PatternSyntaxException pse) {
                //JOptionPane.showMessageDialog(this, "Bad regex pattern for protein!", "Filter Error", JOptionPane.ERROR_MESSAGE);
                //pse.printStackTrace();
            }
        }

        // peptide number filter
        if (peptidesJTextField.getText().length() > 0) {

            try {
                Integer value = new Integer(peptidesJTextField.getText());

                if (peptidesGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("Peptides").getModelIndex()));
                } else if (peptidesEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("Peptides").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("Peptides").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Peptide count has to be an integer!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // coverage filter
        if (coverageJTextField.getText().length() > 0) {

            try {
                Integer value = new Integer(coverageJTextField.getText());

                if (coverageGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("Coverage").getModelIndex()));
                } else if (coverageEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("Coverage").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("Coverage").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Coverage has to be an integer!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // exp count filter
        if (expCountJTextField.getText().length() > 0) {

            try {
                Integer value = new Integer(expCountJTextField.getText());

                if (expCountGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("Exp. Count").getModelIndex()));
                } else if (expCountEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("Exp. Count").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("Exp. Count").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Exp. count has to be an integer!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // fold change filter
        if (foldChangeJTextField.getText().length() > 0) {

            try {
                Double value = new Double(foldChangeJTextField.getText());

                if (foldChangeGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("FC").getModelIndex()));
                } else if (foldChangeEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("FC").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("FC").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Fold change has to be a number!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // p-value filter
        if (pValueJTextField.getText().length() > 0) {

            try {
                Double value = new Double(pValueJTextField.getText());

                if (pValueGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("P-value").getModelIndex()));
                } else if (pValueEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("P-value").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("P-value").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "P-value has to be a number!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // q-value filter
        if (qValueJTextField.getText().length() > 0) {

            try {
                Double value = new Double(qValueJTextField.getText());

                if (qValueGreaterThanJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, value, resultsTable.getColumn("Q-value").getModelIndex()));
                } else if (qValueEqualJRadioButton.isSelected()) {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.EQUAL, value, resultsTable.getColumn("Q-value").getModelIndex()));
                } else {
                    filters.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, value, resultsTable.getColumn("Q-value").getModelIndex()));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Q-value has to be a number!", "Filter Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        RowFilter<Object, Object> allFilters = RowFilter.andFilter(filters);
        ((TableRowSorter) resultsTable.getRowSorter()).setRowFilter(allFilters);

        if (resultsTable.getRowCount() > 0) {
            resultsTable.setRowSelectionInterval(0, 0);
        }

        miTraq.updateResultTableSelection();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearJButton;
    private javax.swing.ButtonGroup coverageButtonGroup;
    private javax.swing.JRadioButton coverageEqualJRadioButton;
    private javax.swing.JRadioButton coverageGreaterThanJRadioButton;
    private javax.swing.JTextField coverageJTextField;
    private javax.swing.JRadioButton coverageLessThanJRadioButton;
    private javax.swing.JButton exitJButton;
    private javax.swing.ButtonGroup expCountButtonGroup;
    private javax.swing.JRadioButton expCountEqualJRadioButton;
    private javax.swing.JRadioButton expCountGreaterThanJRadioButton;
    private javax.swing.JTextField expCountJTextField;
    private javax.swing.JRadioButton expCountLessThanJRadioButton;
    private javax.swing.ButtonGroup foldChangeButtonGroup;
    private javax.swing.JRadioButton foldChangeEqualJRadioButton;
    private javax.swing.JRadioButton foldChangeGreaterThanJRadioButton;
    private javax.swing.JTextField foldChangeJTextField;
    private javax.swing.JRadioButton foldChangeLessThanJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.ButtonGroup pValueButtonGroup;
    private javax.swing.JRadioButton pValueEqualJRadioButton;
    private javax.swing.JRadioButton pValueGreaterThanJRadioButton;
    private javax.swing.JTextField pValueJTextField;
    private javax.swing.JRadioButton pValueLessThanJRadioButton;
    private javax.swing.ButtonGroup peptidesButtonGroup;
    private javax.swing.JRadioButton peptidesEqualJRadioButton;
    private javax.swing.JRadioButton peptidesGreaterThanJRadioButton;
    private javax.swing.JTextField peptidesJTextField;
    private javax.swing.JRadioButton peptidesLessThanJRadioButton;
    private javax.swing.JTextField proteinJTextField;
    private javax.swing.ButtonGroup qValueButtonGroup;
    private javax.swing.JRadioButton qValueEqualJRadioButton;
    private javax.swing.JRadioButton qValueGreaterThanJRadioButton;
    private javax.swing.JTextField qValueJTextField;
    private javax.swing.JRadioButton qValueLessThanJRadioButton;
    // End of variables declaration//GEN-END:variables
}
